blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('posts/', include('posts.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexPage.as_view(), name = 'index'),
    path('about/', views.AboutPage.as_view(), name = 'about'),
]

posts/urls.py
from django.urls import path, include
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all_posts'),
    path('create/', views.CreatePost.as_view(), name = 'create_post')
]

home/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.

# Post
class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=240)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title[0:25]

posts/forms.py
from django.forms import models

from posts.models import Post

class AddPost(models.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

home/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class IndexPage(View):
    template_name =  'home/index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

class AboutPage(View):
    template_name = 'home/about.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

posts/views.py
from django.shortcuts import redirect, render
from django.views import View
from posts.models import Post
from django.contrib import messages
# Create your views here.

class PostList(View):
    template_name =  'posts/post_list.html'

    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, self.template_name, context)

class CreatePost(View):
    template_name = 'posts/post_form.html'
    success_url = 'posts:all_posts'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        Post.objects.create(
            title = request.POST.get('title'),
            text = request.POST.get('text')
        )
        return redirect(self.success_url)

home/templates/home/about.html
{% extends 'home_page.html' %}

{% block title %}
    About
{% endblock title %}
  
{% block content %}
<!-- component -->
<div class="py-16">  
    <div class="container m-auto px-6 text-gray-600 md:px-12 xl:px-6">
        <div class="space-y-6 md:space-y-0 md:flex md:gap-6 lg:items-center lg:gap-12">
          <div class="md:5/12 lg:w-5/12">
            <img src="/img/about-us.jpg" alt="image" loading="lazy" width="" height="">
          </div>
          <div class="md:7/12 lg:w-6/12">
            <h2 class="text-2xl text-gray-900 font-bold md:text-4xl">Nuxt development is carried out by passionate developers</h2>
            <p class="mt-6 text-gray-600">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum omnis voluptatem accusantium nemo perspiciatis delectus atque autem! Voluptatum tenetur beatae unde aperiam, repellat expedita consequatur! Officiis id consequatur atque doloremque!</p>
            <p class="mt-4 text-gray-600"> Nobis minus voluptatibus pariatur dignissimos libero quaerat iure expedita at? Asperiores nemo possimus nesciunt dicta veniam aspernatur quam mollitia.</p>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/index.html
{% extends 'home_page.html' %}

{% block title %}
    Home - Shiva's Blog
{% endblock title %}
  

{% block content %}
<div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
        <!-- <div class="hidden sm:mb-8 sm:flex sm:justify-center">
          <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
            Announcing our next round of funding. <a href="#" class="font-semibold text-indigo-600"><span class="absolute inset-0" aria-hidden="true"></span>Read more <span aria-hidden="true">&rarr;</span></a>
          </div>
        </div> -->
        <div class="text-center">
          <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Welcome to Shiva's Blog</h1>
          <p class="mt-6 text-lg leading-8 text-gray-600">I will post the trending topics to my blog.</p>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <a href="{% url 'posts:all_posts' %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Get started</a>
            <!-- <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Learn more <span aria-hidden="true">→</span></a> -->
          </div>
        </div>
</div>
{% endblock content %}

home/templates/home_page.html
{% extends 'base_master.html' %}

{% block title %}
    Shiva's Blog
{% endblock title %}

{% block body %}
<div class="relative isolate px-6 pt-14 lg:px-8">
    <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
      <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    
    {% block content %}
            
    {% endblock content %}
    
    <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
      <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
  </div>

{% endblock body %}

posts/templates/post_page.html
{% extends 'base_master.html' %}

{% block body %}
<div class="bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Shiva's Blog Posts</h2>
        <p class="mt-2 text-lg leading-8 text-gray-600">Be the first one to Know the trending topics.</p>
        <br>
        <a href="{% url 'posts:create_post' %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
          Add Post
        </a>
      </div>
      
      {% if messages %}
        {{messages}}
      {% endif %}
        
      {% block content %}
        
      {% endblock content %}
        
    </div>
  </div>
  
{% endblock body %}
    

posts/templates/posts/post_form.html
{% extends 'base_master.html' %}

{% block title %}
    Create Post
{% endblock title %}


{% block content %}
  <div class="bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Create Post</h2>
      </div>
      
      <div class="mx-auto mt-10 border-t border-gray-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none lg:grid-cols-3">
        <!-- component -->
        <!-- <div class="flex items-center justify-center p-12"> -->
          <!-- Author: FormBold Team -->
          <!-- Learn More: https://formbold.com -->
          <!-- <div class="mx-auto my-5 w-full max-w-[550px]"> -->
            <form class="" action="" method="POST">
              {% csrf_token %}
              <div class="mb-5">
                <label
                  for="name"
                  class="mb-3 block text-base font-medium text-[#07074D]"
                >
                  Title
                </label>
                <input
                  type="text"
                  name="title"
                  id="title"
                  placeholder="Post Title"
                  required
                  class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                />
              </div>
              
              <div class="mb-5">
                <label
                  for="text"
                  class="mb-3 block text-base font-medium text-[#07074D]"
                >
                  Text
                </label>
                <textarea
                  rows="4"
                  name="text"
                  id="text"
                  placeholder="Type your post text"
                  required
                  class="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                ></textarea>
              </div>
              <div>
                <button
                  class="hover:shadow-form rounded-md bg-[#6A64F1] py-3 px-8 text-base font-semibold text-white outline-none"
                >
                  Submit
                </button>
              </div>
            </form>
          <!-- </div> -->
        <!-- </div> -->
      </div>
        
    </div>
  </div>
{% endblock content %}
    

posts/templates/posts/post_list.html
{% extends 'post_page.html' %}

{% block content %}
<div class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-gray-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none lg:grid-cols-3">
  
  {% for post in posts %}
  <article class="flex max-w-xl flex-col items-start justify-between">
    <div class="flex items-center gap-x-4 text-xs">
      <time datetime="2020-03-16" class="text-gray-500">{{post.date}}</time>
      <!-- <a href="#" class="relative z-10 rounded-full bg-gray-50 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-100">Marketing</a> -->
    </div>
    <div class="group relative">
      <h3 class="mt-3 text-lg font-semibold leading-6 text-gray-900 group-hover:text-gray-600">
        <a href="#">
          <span class="absolute inset-0"></span>
          {{post.title}}
        </a>
      </h3>
      <p class="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">
        {{post.text}}
      </p>
    </div>
    <div class="relative mt-8 flex items-center gap-x-4">
      <img src="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="h-10 w-10 rounded-full bg-gray-50">
      <div class="text-sm leading-6">
        <p class="font-semibold text-gray-900">
          <a href="#">
            <span class="absolute inset-0"></span>
            Michael Foster
          </a>
        </p>
        <!-- <p class="text-gray-600">Co-Founder / CTO</p> -->
      </div>
    </div>
  </article>
  {% endfor %}
    
  
</div>
{% endblock content %}

  

templates/base_master.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
              Shiva's Blog
            {% endblock title %}
        </title>
        <!-- Tailwind CSS -->
        <!-- <script src="https://cdn.tailwindcss.com"></script> -->
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    </head>
    <body>
      <div class="bg-white">
        <header class="absolute inset-x-0 top-0 z-50">
          <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
            <div class="flex lg:flex-1">
              <a href="{% url 'home:index' %}" class="-m-1.5 p-1.5">
                <span class="sr-only">Shiva's Blog</span>
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
              </a>
            </div>
            <div class="flex lg:hidden">
              <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                <span class="sr-only">Open main menu</span>
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
              </button>
            </div>
            <div class="hidden lg:flex lg:gap-x-12">
              <a href="{% url 'home:index' %}" class="text-sm font-semibold leading-6 text-gray-900">Home</a>
              <a href="{% url 'home:about' %}" class="text-sm font-semibold leading-6 text-gray-900">About</a>
              <a href="{% url 'posts:all_posts' %}" class="text-sm font-semibold leading-6 text-gray-900">Blog</a>
              <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Contact</a>
            </div>
            <div class="hidden lg:flex lg:flex-1 lg:justify-end">
              <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a>
            </div>
          </nav>
          <!-- Mobile menu, show/hide based on menu open state. -->
          <div class="lg:hidden" role="dialog" aria-modal="true">
            <!-- Background backdrop, show/hide based on slide-over state. -->
            <div class="fixed inset-0 z-50"></div>
            <div class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
              <div class="flex items-center justify-between">
                <a href="{% url 'home:index' %}" class="-m-1.5 p-1.5">
                  <span class="sr-only">Shiva's Blog</span>
                  <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
                </a>
                <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
                  <span class="sr-only">Close menu</span>
                  <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              <div class="mt-6 flow-root">
                <div class="-my-6 divide-y divide-gray-500/10">
                  <div class="space-y-2 py-6">
                    <a href="{% url 'home:index' %}" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Home</a>
                    <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">About</a>
                    <a href="{% url 'posts:all_posts' %}" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Blog</a>
                    <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Contact</a>
                  </div>
                  <div class="py-6">
                    <a href="#" class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Log in</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>

        {% block body %}
        
          {% block content %}
            
          {% endblock content %}
          
        {% endblock body %}

      </div>
    </body>
</html>